<?php
/**
 * Created by PhpStorm.
 * User: eduardoluz
 * Date: 2018-07-24
 * Time: 2:36 PM
 */

namespace harpya\metaform\button;


class ButtonGroup extends ButtonBase
{

    protected $items = [];

    /**
     * @param SingleButton $btn
     * @return $this
     */
    public function addItem(SingleButton $btn) {
        $id = $btn->getId();
        $this->items[$id] = $btn;
        return $this;
    }

    public function getItems() {
        return $this->items;
    }


    public function render()
    {


        parent::render(); // TODO: Change the autogenerated stub
        if ($this->getContainer()) {
            $view = $this->getContainer()->getForm()->getView();

            $response = $view->fetch('button_group.tpl');

            return $response;
        }

    }

}