<?php
/**
 * Created by PhpStorm.
 * User: eduardoluz
 * Date: 2018-07-24
 * Time: 2:36 PM
 */

namespace harpya\metaform\button;


class SubmitButton extends ButtonBase
{



    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
        if ($this->getContainer()) {
            $view = $this->getContainer()->getForm()->getView();
            return $view->fetch('submit_button.tpl');
        }
    }

}